"use client";
import { Tomorrow } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "@/reducer/store";
import "@/styles/index.css";

const tomorrow = Tomorrow({ weight: "700", subsets: ["latin"] });

// export const metadata = {
//   title: "NexRex",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={tomorrow.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}

